from collections.abc import Awaitable
from collections.abc import Iterator

from httpx import URL
from httpx import AsyncClient
from httpx import Client
from httpx import Request
from httpx import Response
from pydantic_extra_types.semantic_version import SemanticVersion

from .config import ConfigEnum
from .config import ConfigModel
from .enums.path import Path
from .enums.update_url import UpdateUrl
from .models import BannerAndNews
from .models import ClientInfo
from .models import Domain
from .models import GameInfo
from .models import HelloWorld
from .models import Logger
from .models import LoggerConfig
from .models import Manifest
from .models import ManifestUrl
from .models import UpdateInfo
from .models.base import Base
from .models.headers import Headers
from .models.manifest_url_params import ManifestUrlParams
from .types import RelativeZipPath

def parse_json_response_as[T: Base](model_type: type[T], response: Response) -> T | None: ...

class Launcher:
    update_url: UpdateUrl | None = None
    config: ConfigModel
    client: Client

    def __init__(self, config: ConfigModel | ConfigEnum, *, client: Client | None = None) -> None: ...
    def _get_url(self, path: Path | None = None) -> URL: ...
    def _get_headers(self) -> Headers: ...
    def _get_request(self, path: Path, params: ManifestUrlParams | None = None) -> Request: ...
    def _get_response(self, request: Request) -> Response: ...
    def _get_simple_response(self, url: str | URL) -> Response: ...
    def get_update_info(self) -> UpdateInfo | None: ...
    def get_hello_world(self) -> HelloWorld: ...
    def _get_data[T: Base](self, path: Path, params: ManifestUrlParams | None = None, *, data: type[T]) -> T | None: ...
    def get_banner_and_news(self) -> BannerAndNews | None: ...
    def get_client_info(self) -> ClientInfo | None: ...
    def get_domain(self) -> Domain | None: ...
    def get_game_info(self) -> GameInfo | None: ...
    def get_logger(self) -> Logger: ...
    def get_logger_config(self) -> LoggerConfig: ...
    def get_manifest_url(self, version: SemanticVersion, file_path: RelativeZipPath) -> ManifestUrl | None: ...
    def get_manifest(self, manifest_url: ManifestUrl) -> Manifest: ...
    def get_update_file_url(self, update_info: UpdateInfo) -> URL | None: ...
    @staticmethod
    def get_manifest_file_urls(domain: Domain, manifest: Manifest, *, backup: bool = False) -> Iterator[URL]: ...

class AsyncLauncher(Launcher):
    client: AsyncClient

    def __init__(self, config: ConfigModel | ConfigEnum, *, client: Client | None = None) -> None: ...
    def _get_simple_response(self, url: str | URL) -> Awaitable[Response]: ...
    async def get_update_info(self) -> UpdateInfo | None: ...
    async def get_hello_world(self) -> HelloWorld: ...
    async def _get_response(self, request: Request) -> Response: ...
    async def _get_data[T: Base](
        self, path: Path, params: ManifestUrlParams | None = None, *, data: type[T]
    ) -> T | None: ...
    def get_banner_and_news(self) -> Awaitable[BannerAndNews | None]: ...
    def get_client_info(self) -> Awaitable[ClientInfo | None]: ...
    def get_domain(self) -> Awaitable[Domain | None]: ...
    def get_game_info(self) -> Awaitable[GameInfo | None]: ...
    def get_logger(self) -> Awaitable[Logger]: ...
    def get_logger_config(self) -> Awaitable[LoggerConfig]: ...
    def get_manifest_url(
        self, version: SemanticVersion, file_path: RelativeZipPath
    ) -> Awaitable[ManifestUrl | None]: ...
    async def get_manifest(self, manifest_url: ManifestUrl) -> Manifest: ...
